#!/bin/bash
#Licensed Materials - Property of IBM
#“Restricted Materials of IBM”
#5765-R17
#© Copyright IBM Corp. 2020 All Rights Reserved.
#US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp

# Feteches the output from the output file
if [ $# -ne 5 ]
then
  echo "Usage: ./postprocess c1 c2 c3 c4 c5"
else
  c1=${1}
  c2=${2}
  c3=${3}
  c4=${4}
  c5=${5}

  baseDir=`pwd`
  cd ${baseDir}/cylinder-${c1}-${c2}-${c3}-${c4}-${c5}

  tKinEn=`tail -1 cylinderAndBackground/postProcessing/probes/0/k | awk '{ print $2 }'`
  echo "$c1 $c2 $c3 $c4 $c5 $tKinEn" > cost.out
  echo $tKinEn
fi
