#!/bin/bash
#Licensed Materials - Property of IBM
#“Restricted Materials of IBM”
#5765-R17
#© Copyright IBM Corp. 2020 All Rights Reserved.
#US Government Users Restricted Rights - Use, duplication or disclosure restricted by GSA ADP Schedule Contract with IBM Corp

# Create simulation skeleton
if [ $# -ne 5 ]
then
  echo "Usage: ./preprocess c1 c2 c3 c4 c5"
else
  c1=${1}
  c2=${2}
  c3=${3}
  c4=${4}
  c5=${5}

  baseDir=`pwd`
  templateDir="${baseDir}/template"
  simDir="${baseDir}/cylinder-${c1}-${c2}-${c3}-${c4}-${c5}"

  timestp=`date +%Y%m%d.%H%M%S`
  if [ -d $simDir ]
  then
    mv $simDir ${simDir}.$timestp
  fi
  cp -r $templateDir $simDir 
fi
